name: Wake Up Streamlit App

on:
  schedule:
    # 毎日UTC 00:00 (JST 09:00) に実行
    # ここは必要に応じて調整してください
    - cron: "0 0 * * *"
  workflow_dispatch:
    # 手動でワークフローを実行できるようにする

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Streamlit App
        run: |
          # ここにあなたのStreamlitアプリのURLを記述してください
          # 例: https://your-app-name.streamlit.app
          APP_URL="あなたのStreamlitアプリのURL"

          echo "Sending GET request to $APP_URL"
          curl -sS --fail $APP_URL || { echo "Failed to reach Streamlit App"; exit 1; }
          echo "Successfully reached Streamlit App"
